Repository molgenis/molgenis-emx2, pull requests merged in 2024-05, with the labels that each got.

#3673 fix: only include variables that that part of a model
  apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/index.vue
Labels: ssr-catalogue

#3706 fix: dropped main element
  apps/molgenis-viz/src/components/layouts/Page.vue
Labels: dashboards

#3710 fix: corrected param names
  apps/cranio-provider/src/views/provider-clp-all-centers.vue
  apps/cranio-provider/src/views/provider-cs-center-surgical.vue
  apps/cranio-public/src/views/view-public-dashboard.vue
  apps/ern-genturis/src/views/view-public-dashboard.vue
  apps/ern-ithaca/src/views/view-dashboard.vue
  apps/ern-skin/src/views/view-public-dashboard.vue
  apps/molgenis-viz/src/views/viz-geo-mercator.vue
Labels: dashboards

#3656 feat: filter variables on cohort variable mapping
  .circleci/config.yml
  apps/nuxt3-ssr/components/filter/List.vue
  apps/nuxt3-ssr/components/filter/Ontology.vue
  apps/nuxt3-ssr/components/filter/Sidebar.vue
  apps/nuxt3-ssr/error.vue
  apps/nuxt3-ssr/interfaces/types.ts
  apps/nuxt3-ssr/pages/[schema]/ssr-catalogue/[catalogue]/variables/index.vue
  apps/nuxt3-ssr/utils/buildQueryFilter.test.ts
  apps/nuxt3-ssr/utils/buildQueryFilter.ts
  apps/tailwind-components/app.vue
  apps/tailwind-components/components/input/List.vue
  apps/tailwind-components/pages/InputList.story.vue
  apps/tailwind-components/types/types.ts
  e2e/tests/catalogue/search-results-count.spec.ts
  e2e/tests/catalogue/variable-cohort-filter.spec.ts
Labels: priority, ssr-catalogue

#3747 fix: proper handling of 'na' values
  tools/pyclient/dev/demodata/Pet.csv
  tools/pyclient/dev/dev.py
  tools/pyclient/src/molgenis_emx2_pyclient/client.py
Labels: emx2_python_client

#3748 fix: removed bottom margin in breadcrumbs
  apps/molgenis-components/public/theme.css
  backend/molgenis-emx2-webapi/src/main/resources/theme/bootstrap46/_breadcrumb.scss
Labels: look and feel

#3746 fix: updated css resets; changed footer element
  apps/molgenis-viz/src/App.vue
  apps/molgenis-viz/src/components/layouts/PageFooter.vue
  apps/molgenis-viz/src/styles/resets.scss
Labels: dashboards

#3705 feat: aggregation dashboard
  apps/aggregation-dashboard/index.html
  apps/aggregation-dashboard/jsconfig.json
  apps/aggregation-dashboard/package.json
  apps/aggregation-dashboard/public/aggregation-header.jpg
  apps/aggregation-dashboard/src/App.vue
  apps/aggregation-dashboard/src/interfaces/types.ts
  apps/aggregation-dashboard/src/main.js
  apps/aggregation-dashboard/src/router/index.js
  apps/aggregation-dashboard/src/styles/index.scss
  apps/aggregation-dashboard/src/styles/variables.scss
  apps/aggregation-dashboard/src/utils/index.ts
  apps/aggregation-dashboard/src/views/view-dashboard.vue
  apps/aggregation-dashboard/tsconfig.json
  apps/aggregation-dashboard/vite.config.js
  apps/package.json
  apps/yarn.lock
Labels: dashboards

#3784 feat: init structure for imdhub-public
  apps/imdhub-public/.gitignore
  apps/imdhub-public/index.html
  apps/imdhub-public/package.json
  apps/imdhub-public/public/recon4imd.png
  apps/imdhub-public/public/recon4imd_header.jpg
  apps/imdhub-public/src/App.vue
  apps/imdhub-public/src/components/AppFooter.vue
  apps/imdhub-public/src/main.js
  apps/imdhub-public/src/router/index.js
  apps/imdhub-public/src/styles/index.scss
  apps/imdhub-public/src/views/view-about.vue
  apps/imdhub-public/src/views/view-dashboard.vue
  apps/imdhub-public/src/views/view-documents.vue
  apps/imdhub-public/src/views/view-home.vue
  apps/imdhub-public/src/views/view-request-access.vue
  apps/imdhub-public/tsconfig.json
  apps/imdhub-public/vite.config.js
  apps/package.json
  apps/yarn.lock
Labels: dashboards
